name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: 'myassignment-426912'
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Store your service account key as a secret in GitHub

      - name: Authenticate Docker with Google Cloud
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image

      - name: Deploy to Google Cloud
        run: |
          gcloud compute instances create-with-container assignment --container-image us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image
        env:
          CLOUDSDK_COMPUTE_REGION: us-central1
          CLOUDSDK_COMPUTE_ZONE: us-central1-a
