name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: 'docker://gcr.io/cloud-builders/docker'
        with:
          args: build -t us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image .

      - name: Push Docker image
        uses: 'docker://gcr.io/cloud-builders/docker'
        with:
          args: push us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image

      - name: Deploy to Google Cloud
        uses: 'docker://gcr.io/google.com/cloudsdktool/cloud-sdk'
        with:
          entrypoint: gcloud
          args: compute instances create-with-container assignment --container-image us-central1-docker.pkg.dev/myassignment-426912/cloud-run-source-deploy/image
        env:
          CLOUDSDK_COMPUTE_REGION: us-central1
          CLOUDSDK_COMPUTE_ZONE: us-central1-a
